/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_BUTTON_2 (GUI_ID_USER + 0x03)
#define ID_BUTTON_3 (GUI_ID_USER + 0x04)
#define ID_BUTTON_4 (GUI_ID_USER + 0x05)
#define ID_BUTTON_5 (GUI_ID_USER + 0x06)
#define ID_BUTTON_6 (GUI_ID_USER + 0x07)
#define ID_BUTTON_7 (GUI_ID_USER + 0x08)
#define ID_BUTTON_8 (GUI_ID_USER + 0x09)
#define ID_BUTTON_9 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10 (GUI_ID_USER + 0x0B)
#define ID_TEXT_0 (GUI_ID_USER + 0x0C)
#define ID_EDIT_0 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_11 (GUI_ID_USER + 0x0E)


// USER START (Optionally insert additional defines)
extern WM_HWIN Createbomb(void);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)


// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_0, 191, 110, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_1, 191, 160, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_2, 291, 60, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "C", ID_BUTTON_3, 291, 110, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "E", ID_BUTTON_4, 291, 160, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_5, 191, 60, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_6, 141, 110, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_7, 141, 160, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_8, 241, 60, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_9, 241, 160, 45, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_10, 241, 110, 45, 45, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 167, 218, 147, 32, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 96, 9, 290, 43, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "1", ID_BUTTON_11, 141, 60, 45, 45, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
char number[2]=" 0";

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:

    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0000));
    TEXT_SetText(hItem, "NTUST");
    TEXT_SetFont(hItem, GUI_FONT_32_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_32_1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    if(number[1]=='0'&&number[0]==' ')
					{
					 number[1]='5';
			     EDIT_SetText(hItem,number);
					}
					else if(number[0]==' ')
					{
						number[0]=number[1];
						number[1]='5';
						EDIT_SetText(hItem,number);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			    
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    if(number[1]=='0'&&number[0]==' ')
					{
					 number[1]='8';
			     EDIT_SetText(hItem,number);
					}
					else if(number[0]==' ')
					{
						number[0]=number[1];
						number[1]='8';
						EDIT_SetText(hItem,number);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    if(number[1]=='0'&&number[0]==' ')
					{
					 number[1]='0';
			     EDIT_SetText(hItem,number);
					}
					else if(number[0]==' ')
					{
						number[0]=number[1];
						number[1]='0';
						EDIT_SetText(hItem,number);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'C'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    number[0]=' ';
			    number[1]='0';
			    EDIT_SetText(hItem,number);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'E'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			    if(number[0]==' '&&number[1]<'5')
					{
						number[0]=' ';
						number[1]='5';
					}
          Createbomb();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by '2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    if(number[1]=='0'&&number[0]==' ')
					{
					 number[1]='2';
			     EDIT_SetText(hItem,number);
					}
					else if(number[0]==' ')
					{
						number[0]=number[1];
						number[1]='2';
						EDIT_SetText(hItem,number);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    if(number[1]=='0'&&number[0]==' ')
					{
					 number[1]='4';
			     EDIT_SetText(hItem,number);
					}
					else if(number[0]==' ')
					{
						number[0]=number[1];
						number[1]='4';
						EDIT_SetText(hItem,number);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by '7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    if(number[1]=='0'&&number[0]==' ')
					{
					 number[1]='7';
			     EDIT_SetText(hItem,number);
					}
					else if(number[0]==' ')
					{
						number[0]=number[1];
						number[1]='7';
						EDIT_SetText(hItem,number);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by '3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    if(number[1]=='0'&&number[0]==' ')
					{
					 number[1]='3';
			     EDIT_SetText(hItem,number);
					}
					else if(number[0]==' ')
					{
						number[0]=number[1];
						number[1]='3';
						EDIT_SetText(hItem,number);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by '9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    if(number[1]=='0'&&number[0]==' ')
					{
					 number[1]='9';
			     EDIT_SetText(hItem,number);
					}
					else if(number[0]==' ')
					{
						number[0]=number[1];
						number[1]='9';
						EDIT_SetText(hItem,number);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by '6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    if(number[1]=='0'&&number[0]==' ')
					{
					 number[1]='6';
			     EDIT_SetText(hItem,number);
					}
					else if(number[0]==' ')
					{
						number[0]=number[1];
						number[1]='6';
						EDIT_SetText(hItem,number);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by '1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			    if(number[1]=='0'&&number[0]==' ')
					{
					 number[1]='1';
			     EDIT_SetText(hItem,number);
					}
					else if(number[0]==' ')
					{
						number[0]=number[1];
						number[1]='1';
						EDIT_SetText(hItem,number);
					}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
